package starling.core;

extern class Starling extends starling.events.EventDispatcher {
	var antiAliasing : Int;
	var backBufferHeight(default,never) : Int;
	var backBufferWidth(default,never) : Int;
	var contentScaleFactor__(default,never) : Float;
	var contextData(default,never) : flash.utils.Dictionary;
	var context__(default,never) : flash.display3D.Context3D;
	var enableErrorChecking : Bool;
	var isStarted(default,never) : Bool;
	var juggler__(default,never) : starling.animation.Juggler;
	var nativeOverlay(default,never) : flash.display.Sprite;
	var nativeStage(default,never) : flash.display.Stage;
	var profile(default,never) : String;
	var root(default,never) : starling.display.DisplayObject;
	var shareContext : Bool;
	var showStats : Bool;
	var simulateMultitouch : Bool;
	var stage(default,never) : starling.display.Stage;
	var stage3D(default,never) : flash.display.Stage3D;
	var supportHighResolutions : Bool;
	var touchProcessor : starling.events.TouchProcessor;
	var viewPort : flash.geom.Rectangle;
	function new(p1 : Class<Dynamic>, p2 : flash.display.Stage, ?p3 : flash.geom.Rectangle, ?p4 : flash.display.Stage3D, ?p5 : String, ?p6 : String) : Void;
	function advanceTime(p1 : Float) : Void;
	function deleteProgram(p1 : String) : Void;
	function dispose() : Void;
	function getProgram(p1 : String) : flash.display3D.Program3D;
	function hasProgram(p1 : String) : Bool;
	function makeCurrent() : Void;
	function nextFrame() : Void;
	function registerProgram(p1 : String, p2 : flash.utils.ByteArray, p3 : flash.utils.ByteArray) : flash.display3D.Program3D;
	function registerProgramFromSource(p1 : String, p2 : String, p3 : String) : flash.display3D.Program3D;
	function render() : Void;
	function showStatsAt(?p1 : String, ?p2 : String, p3 : Float = 1) : Void;
	function start() : Void;
	function stop(p1 : Bool = false) : Void;
	static var VERSION : String;
	static var contentScaleFactor(default,never) : Float;
	static var context(default,never) : flash.display3D.Context3D;
	static var current(default,never) : Starling;
	static var handleLostContext : Bool;
	static var juggler(default,never) : starling.animation.Juggler;
	static var multitouchEnabled : Bool;
}
